### ISSUE TITLE
Close bracket not linked

### ISSUE THREAD

**Issue by yennycheung** [rrshaban/SwatCoRe#63]
![image](https://cloud.githubusercontent.com/assets/6254293/14412887/6c7ca8f8-ff39-11e5-8ee7-7708a02155a5.png)

**Comment by rrshaban** [comment]
@yennycheung thanks for putting these up! I'll fix this one once I can find it

**Comment by yennycheung** [comment]
Hey hope you don't mind, I had some time just now and I fixed it.

**Comment by rrshaban** [comment]
Thanks!
